import {
  Box,
  Button,
  Center,
  Container,
  HStack,
  Image,
  List,
  ListIcon,
  ListItem,
  Text,
} from "@chakra-ui/react";
import type { NextPage } from "next";
import { signIn } from "next-auth/react";
import Head from "next/head";

import { GoMarkGithub } from "react-icons/go";
import { MdCheckCircle } from "react-icons/md";

import ilustration from "../assets/ilustration.jpeg";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Kambann</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxW="100%" maxH="100%" paddingX="10%" bg="white">
        <HStack justifyContent="center">
          <Box>
            <Text fontSize="2xl" fontWeight="bold" marginY="5%">
              Kambann is a simple tool to create kanban boards.
            </Text>
            <List spacing={3}>
              <ListItem fontSize="xl">
                <ListIcon as={MdCheckCircle} color="green.500" />
                Create your projects
              </ListItem>
              <ListItem fontSize="xl">
                <ListIcon as={MdCheckCircle} color="green.500" />
                Invite to your teams
              </ListItem>
              <ListItem fontSize="xl">
                <ListIcon as={MdCheckCircle} color="green.500" />
                Create a custom task list
              </ListItem>
              <ListItem fontSize="xl">
                <ListIcon as={MdCheckCircle} color="green.500" />
                Assign the tasks
              </ListItem>
            </List>
            <Center marginY="50px">
              <Box bg="gray.700" rounded={8} _hover={{ bg: "gray.600" }}>
                <Button
                  colorScheme="WhiteAlpha"
                  leftIcon={<GoMarkGithub />}
                  onClick={() => signIn("github", { callbackUrl: "/projects" })}
                >
                  Start with Github
                </Button>
              </Box>
            </Center>
          </Box>
          <Box>
            <Image src={ilustration.src} alt="kanban ilustration" />
          </Box>
        </HStack>
      </Container>
    </>
  );
};

export default Home;
